"""Initial migration.

Revision ID: 8a6a5432094e
Revises: 
Create Date: 2020-05-26 18:49:38.491954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a6a5432094e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nim', sa.String(length=10), nullable=True),
    sa.Column('nama', sa.String(length=25), nullable=True),
    sa.Column('kelas', sa.String(length=10), nullable=True),
    sa.Column('alamat', sa.String(length=52), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nim')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('data')
    # ### end Alembic commands ###
